name: Deploy to GitHub Pages
on: 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Set GitHub E-mail
        run: git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Set GitHub Name
        run: git config --global user.name "${{ github.actor }}"
      - name: Setup Dependencies
        run: npm install
      - name: Deploy to GitHub Pages
        run: npm run deploy
